### ISSUE TITLE
Plugin upload_file can't upload files

### ISSUE THREAD

**Issue by NativoDigital** [Octopoos/SEBLOD#133]
Hello,

Since Joomla update to 3.4.4, upload_file returns this message when trying to upload a file:

Warning: File /sitepath/downloads/666/file.zip not uploaded for security reasons!

Then it adds the entry on the database with a wrong path, without the id part, when it is marked as "one folder one content". It also creates the directory but the file doesn't upload due to the reason it gives.

It works on 3.4.3 and before. It does not work on 3.4.4 and above.

Any help will be appreciated.
Thank you.
Kind regards

**Comment by NativoDigital** [comment]
This issue can be a consequence of this one: https://github.com/joomla/joomla-cms/pull/7814

**Comment by sebastienheraud** [comment]
Hi,
This has been fixed here: https://github.com/Octopoos/SEBLOD/commit/f0cd1e1e3cb5af5bdb033b859be9b259f76460ef
And.. it will be available in upcoming SEBLOD 3.8.0 release.
Thanks,
Saba.

**Comment by NativoDigital** [comment]
Once again, thank you very much Saba.

I await the upcoming Seblod release with a lot of interest.

Kind regards.
-Adonay

**Comment by pulsarinformatique** [comment]
Hi
as reported on http://www.seblod.com/community/forums/general-discussions/zip-file-upload-impossible-since-joomla-3-4-5#post39901 the fix doesn't seem to be included or there is something missing since the issue is still here

thanks

cyril

**Comment by sebastienheraud** [comment]
Hi Cyril,
You should enable the suitable parameter.
Please read the changlog http://www.seblod.com/changelogs#SEBLOD_380_20160430
Saba.
